"""Strict CP-01 domain models and canonical serialization helpers."""

from __future__ import annotations

from proof.domain.common import (
    Confidence,
    Evidence,
    EvidenceClass,
    EvidenceRef,
    FrozenModel,
    JsonValue,
    KnownValue,
    ProvenanceKind,
    ResourceId,
    Sha256,
    StabilizationPolicy,
    StatePlane,
    UtcTime,
    Uuid7,
    canonical_bytes,
    content_hash,
    is_uuid7,
    uuid7,
)
from proof.domain.context import (
    Approval,
    Assertion,
    Constraint,
    ContextEnvelope,
    Intent,
    Invariant,
    InvariantKind,
    PolicyReference,
    PredicateOperator,
    SafetyContract,
    ScopeSelector,
    StatePredicate,
    TemporaryException,
)
from proof.domain.coverage import CompareResult, CoverageCell, CoverageRecord, RegressionCase
from proof.domain.effects import (
    ActionEvent,
    CausalLink,
    DerivedEffect,
    Effect,
    MutationEvent,
    ObservedAction,
    RequestedAction,
    RiskLevel,
    SemanticCategory,
)
from proof.domain.errors import ErrorOwner, ProofError, RetryAction
from proof.domain.ir import (
    CanonicalResourceState,
    InfrastructureIR,
    Relationship,
    RelationshipType,
    Resource,
    ResourceCriticality,
    ResourceIdentity,
    ResourceProperty,
    StateSnapshot,
    WorldState,
)
from proof.domain.run import (
    AgentDefinition,
    CheckStatus,
    RunEvent,
    RunManifest,
    RunResult,
    RunVerdict,
    Severity,
    TrialDisposition,
    VerifierResult,
    WorldDefinition,
)
from proof.domain.scenario import (
    FaultInstance,
    FaultOperator,
    FidelityRequirement,
    HealthOracle,
    ParameterSpec,
    Scenario,
    ScenarioManifest,
)

DOMAIN_SCHEMA_MODELS: dict[str, type[FrozenModel]] = {
    "evidence": Evidence,
    "known-value": KnownValue,
    "stabilization-policy": StabilizationPolicy,
    "resource-identity": ResourceIdentity,
    "resource-property": ResourceProperty,
    "resource": Resource,
    "relationship": Relationship,
    "infrastructure-ir": InfrastructureIR,
    "canonical-resource-state": CanonicalResourceState,
    "state-snapshot": StateSnapshot,
    "world-state": WorldState,
    "assertion": Assertion,
    "scope-selector": ScopeSelector,
    "state-predicate": StatePredicate,
    "intent": Intent,
    "approval": Approval,
    "temporary-exception": TemporaryException,
    "policy-reference": PolicyReference,
    "constraint": Constraint,
    "context-envelope": ContextEnvelope,
    "invariant": Invariant,
    "safety-contract": SafetyContract,
    "effect": Effect,
    "mutation-event": MutationEvent,
    "action-event": ActionEvent,
    "causal-link": CausalLink,
    "requested-action": RequestedAction,
    "observed-action": ObservedAction,
    "derived-effect": DerivedEffect,
    "run-event": RunEvent,
    "parameter-spec": ParameterSpec,
    "fidelity-requirement": FidelityRequirement,
    "health-oracle": HealthOracle,
    "fault-operator": FaultOperator,
    "fault-instance": FaultInstance,
    "scenario": Scenario,
    "scenario-manifest": ScenarioManifest,
    "agent-definition": AgentDefinition,
    "world-definition": WorldDefinition,
    "run-manifest": RunManifest,
    "verifier-result": VerifierResult,
    "run-result": RunResult,
    "regression-case": RegressionCase,
    "coverage-cell": CoverageCell,
    "coverage-record": CoverageRecord,
    "compare-result": CompareResult,
}


__all__ = [
    "DOMAIN_SCHEMA_MODELS",
    "ActionEvent",
    "AgentDefinition",
    "Approval",
    "Assertion",
    "CanonicalResourceState",
    "CausalLink",
    "CheckStatus",
    "CompareResult",
    "Confidence",
    "Constraint",
    "ContextEnvelope",
    "CoverageCell",
    "CoverageRecord",
    "DerivedEffect",
    "Effect",
    "ErrorOwner",
    "Evidence",
    "EvidenceClass",
    "EvidenceRef",
    "FaultInstance",
    "FaultOperator",
    "FidelityRequirement",
    "FrozenModel",
    "HealthOracle",
    "InfrastructureIR",
    "Intent",
    "Invariant",
    "InvariantKind",
    "JsonValue",
    "KnownValue",
    "MutationEvent",
    "ObservedAction",
    "ParameterSpec",
    "PolicyReference",
    "PredicateOperator",
    "ProofError",
    "ProvenanceKind",
    "RegressionCase",
    "Relationship",
    "RelationshipType",
    "RequestedAction",
    "Resource",
    "ResourceCriticality",
    "ResourceId",
    "ResourceIdentity",
    "ResourceProperty",
    "RetryAction",
    "RiskLevel",
    "RunEvent",
    "RunManifest",
    "RunResult",
    "RunVerdict",
    "SafetyContract",
    "Scenario",
    "ScenarioManifest",
    "ScopeSelector",
    "SemanticCategory",
    "Severity",
    "Sha256",
    "StabilizationPolicy",
    "StatePlane",
    "StatePredicate",
    "StateSnapshot",
    "TemporaryException",
    "TrialDisposition",
    "UtcTime",
    "Uuid7",
    "VerifierResult",
    "WorldDefinition",
    "WorldState",
    "canonical_bytes",
    "content_hash",
    "is_uuid7",
    "uuid7",
]
